apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stakater-kube-linting
  labels:
    app.kubernetes.io/version: "{{ .Chart.Version }}"
spec:
  params:
    - description: Path/Folder for the k8s deployment files to check
      name: DEPLOYMENT_FILES_PATH
      type: string
    - description: File name for the helm hydrated manifests
      name: FILE
      type: string
  steps:
    - image: ghcr.io/stakater/pipeline-toolbox:v0.0.42
      name: helm      
      env:
        - name: TENANT
          valueFrom:
            secretKeyRef:
              name: pipeline-config
              key: tenant
              optional: true
      script: |
        cd $(params.DEPLOYMENT_FILES_PATH)
        helm dependency build .
        # helm template 
        helm template . > $(params.FILE)
        # run helm install dryrun
        helm install tekton-test-release . --dry-run -n "${TENANT}-build"
      workingDir: $(workspaces.source.path)
    - image: docker.io/stackrox/kube-linter:0.2.2-2-g7d10a69154-alpine@sha256:e520e9d8d3a2dfa611914836536545b135845e7bda9f1df34b060e116232dbf0
      name: kube-lint
      script: |
        mv ../../kube-linter ../../bin;
        kube-linter lint .
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
    
